server:
  port: 8206

mybatis-plus:
  type-enums-package: com.hjh.hhyx.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-user?characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: jiang071511

  redis:
    host: localhost #121.36.77.255
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

wx:
  open:
    # 小程序微信公众平台appId
    app_id: wx7ac0d70107907fd0
    # 小程序微信公众平台api秘钥
    app_secret: 2ce9772102243f0ca79340e1ad5842a2